### ISSUE TITLE
OneTrust.AllowAll() method available

### ISSUE THREAD

**Issue by Silinde87** [Peoople/react-native-onetrust-cmp#2]
Is [AllowAll](https://developer.onetrust.com/onetrust/docs/javascript-api#allow-all-consent) method available in this library? If not, is it planned to be included in future versions?

I have gone through all the [documentation](https://www.npmjs.com/package/react-native-onetrust-cmp) and have not been able to find it.

**Comment by javiergarmon** [comment]
Sorry, this is not the official repo, just a fork.
